# Generated by Django 4.2.13 on 2024-06-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Announcements',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
            options={
                'verbose_name': 'Modify Courses Section',
                'verbose_name_plural': 'Modify Courses Section',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing/')),
            ],
            options={
                'verbose_name': 'Landing Page Image',
                'verbose_name_plural': 'Landing Page Image',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team/')),
            ],
            options={
                'verbose_name': 'Modify Team Section',
                'verbose_name_plural': 'Modify Team Section',
            },
        ),
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='why/')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Modify (Why enroll) Section',
                'verbose_name_plural': 'Modify (Why enroll) Section',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='enduser.category')),
            ],
            options={
                'verbose_name': 'Add or Remove Subjects',
                'verbose_name_plural': 'Add or Remove Subjects',
            },
        ),
    ]
