# Generated by Django 4.2.13 on 2024-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Type a new announcement here.')),
                ('image', models.ImageField(default='default.jpg', upload_to='announcementBar/')),
                ('expiration_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Announcement Bar',
                'verbose_name_plural': 'Announcement Bars',
            },
        ),
    ]
