# Generated by Django 4.2.13 on 2024-06-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0002_announcementbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementbar',
            name='image',
        ),
    ]
